project:
  type: website
  output-dir: docs
  
website:
  page-navigation: true
  title: "Cho's FinBlog"
  favicon: logo.png
  site-url: https://jo-cho.github.io/FinBlog/
  repo-url: https://github.com/jo-cho/FinBlog
  repo-actions: [issue]
  description: "금융 공부 블로그"
  navbar:
    right:
      - about.qmd
      - icon: github
        menu: 
        - text: Source Code
          href: https://github.com/jo-cho/FinBlog/tree/main/docs
        - text: Report a Bug
          href: https://github.com/jo-cho/FinBlog/issues
  sidebar:
    pinned: true
    style: docked
    collapse-level: 1
    header: "FinBlog"
    contents:
      - href: index.qmd
        text: "홈"
      - href: listing.qmd
        text: "모든 글 보기"
      - section: "금융 데이터 처리"
        contents:
          - href: posts/fin_data/Fractional_difference.ipynb
            text: "분수 차분"
      - section: "알고리즘 트레이딩"
        contents:
          - href: posts/ml_trading/0_Introduction.ipynb
            text: "트레이딩 개요"
          - href: posts/ml_trading/1_Get_Market_Data.ipynb
            text: "시장 데이터 수집"
          - href: posts/ml_trading/2_Labeling.ipynb
            text: "가격 모멘텀 라벨링"
          - href: posts/ml_trading/3_Get_Features.ipynb
            text: "피쳐 생성"
          - href: posts/ml_trading/4_Feature_Selection.ipynb
            text: "피쳐 선정"
          - href: posts/ml_trading/5_Get_Trading_Signals.ipynb
            text: "매매 시그널 분류"
          - href: posts/ml_trading/6_Trading_Rules.ipynb
            text: "매매 규칙"
          - href: posts/ml_trading/7_Enhancing_and_Bet_Confidence.ipynb
            text: "매매 신뢰도 측정과 전략 강화"
      - section: "시스템 리스크 분석"
        contents:
          - href: posts/systemic_risk/1_Systemic_Risk.ipynb
            text: "시스템 리스크 개념"
          - section: "시스템 리스크 측정 - 선행연구"
            contents:
            - href: posts/systemic_risk/2_Systemic_Risk_Measures.ipynb
              text: "시스템 리스크 측정 - 선행연구 요약"
            - href: posts/systemic_risk/2-1_Systemic_Risk_Measures_Macro.ipynb
              text: "시스템 리스크 측정 - 선행연구 (거시경제)"
            - href: posts/systemic_risk/2-2_Systemic_Risk_Measures_Market.ipynb
              text: "시스템 리스크 측정 - 선행연구 (시장위험)"      
            - href: posts/systemic_risk/2-3_Systemic_Risk_Measures_Cross-sectional.ipynb
              text: "시스템 리스크 측정 - 선행연구 (금융기관 위험)"
            - href: posts/systemic_risk/2-4_Systemic_Risk_Measures_Probability_of_Default.ipynb
              text: "시스템 리스크 측정 - 선행연구 (부도확률모형 위험)"
            - href: posts/systemic_risk/2-5_Systemic_Risk_Measures_Network.ipynb
              text: "시스템 리스크 측정 - 선행연구 (네트워크)"
          - section: "시스템 리스크와 머신러닝"
            contents:
            - href: posts/systemic_risk/3_Systemic_Risk_And_Machine_Learning_1.ipynb
              text: "시스템 리스크와 머신러닝 - 선행연구1"
            - href: posts/systemic_risk/3_Systemic_Risk_And_Machine_Learning_1_2.ipynb
              text: "시스템 리스크와 머신러닝 - 선행연구2"
            - href: posts/systemic_risk/3_Systemic_Risk_And_Machine_Learning_2.ipynb
              text: "시스템 리스크와 머신러닝 - 향후 연구 방향"
      - section: "그래프 머신러닝"
        contents:
          - href: posts/machine_learning/GRL_01.ipynb
            text: "들어가며"
          - href: posts/machine_learning/GRL_02_1.ipynb
            text: "그래프 통계량과 커널 방법"
          - href: posts/machine_learning/GRL_02_2.ipynb
            text: "이웃중복 감지"
format:
  html:
    theme: flatly
    css: styles.css
    fontsize: 1.1em

        
editor: visual